spring:
  datasource:
    url: jdbc:postgresql://localhost:65532/testcase
    username:  ${USER_NAME:postgres}
    password: ${PASSWORD:secret}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
