CREATE TABLE IF NOT EXISTS "CLIENT" (
    "DOCUMENT" VARCHAR(14) NOT NULL,
	"DOCUMENT_TYPE" VARCHAR(4) NOT NULL,
	"NAME" VARCHAR(64) NOT NULL,
	"EMAIL" VARCHAR(255),
	"DELETED_DATE" TIMESTAMP,
	"DELETED" CHAR(1) NULL DEFAULT 'N',
	PRIMARY KEY ("DOCUMENT", "DOCUMENT_TYPE")
)